<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FornecedorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('fornecedors')->insert(['nome' => '', 'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Active Pharmaceutica', 'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Adicel Matriz',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Agargel',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'AGES',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Akron',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Alianza',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Allpremium Industria',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Analitic',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Aplinova',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Aqia Biotec',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Aqia Quimica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Arbros Pharma & Food',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Attivos Magistrais',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Attriom',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Ayalla',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Barry Callebaut',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Beneo',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'BioChemicals',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Biodiversité',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Biovital',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Chemyunion',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Clover',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Coana',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Condor',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'CoperVet',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Corantec',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Cosfito',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'D.A Brasil',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Destilaria Bauru',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Distriol',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Doce Sabor Industria de Prod. Alim.',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Dods Com e Dist de Insumos e Embalagens',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'DSM Produtos Nutricionais Brasil SA',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Emanuel Bernardino de Sene',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Embracaps',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Embrafarma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Enovate Biolife',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Essentia Pharma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Essential',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Exata',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Excipienta',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Fagron',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Fassim',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Ferquimica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Finquimica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Florien',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Formus Magistral',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Galena',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Gamma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'GastronomyLab',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Gelita',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Giassi Supermercados',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Givaudan',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Globulus Inertis Homeopaticos Ltda',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Grasse Aromas e Ingredientes Ltda.',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'GW Distribuição',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Harmonie',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Henrifarma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Iberoquimica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Indukern',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Infinity',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Inlab',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'INP Industria de Alimentos',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Irial Mag',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Itacaps Produtos Naturais',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Jovii',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Kin Master',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'King Herbs',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'L Kuzma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Labsynth',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Lasenor',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Le Antoni',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Lemma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Mase',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Maypro',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Mundo dos Óleos',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nanovetores',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Natural Pro',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Naturell',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Neon',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nexxira',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nilab',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nourion',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'NPA',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nugali',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nutramax',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Nutrifarm',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Organic',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Orgolabs',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Orgomax',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Ozon Care',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Pazze',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Pharma Nostra',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Pharmaspecial',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'PHD',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Philozon',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Pholias',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'PnFarma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Primaceutica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Probiotical',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Protesa',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Prozyn',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Purifarma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Quimiformula',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Rija Importação',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sabara Química',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sabinsa',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sarfam',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Schraiber',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sigma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Silvestre',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sintética',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sixty Pharma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'SM Empreendimentos',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Solutaste',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sovitá',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Stauber',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Stevia Farma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sustentec',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Sweetmix',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Synergy Aromas',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Synth',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Tovani Benzaquen',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Valdequímica',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Vepakum Farma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Via Pharma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Vidara do Brasil Química',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Vogler',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Volp',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'VPK Farma',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Wacker',  'telefone' => '', 'cep' => '', 'cnpj' => '']);
        DB::table('fornecedors')->insert(['nome' => 'Xian Ceres',  'telefone' => '', 'cep' => '', 'cnpj' => '']);

    }
}
